CREATE USER Test1_100 IDENTIFIED BY mckvie2024 PASSWORD EXPIRE;

-- But for Oracle express edition 
-- CREATE USER CR#Test1_100 IDENTIFIED BY mckvie2024 PASSWORD EXPIRE; 
-- OR 
-- CREATE USER C##Test1_100 IDENTIFIED BY mckvie2024 PASSWORD EXPIRE;